### ISSUE TITLE
Banner image hides blog content when opening entry

### ISSUE THREAD

**Issue by GeckoEidechse** [Alystrasz/NorthstarBlog#6]
Video showcasing the issue:

[Screencast from 2023-11-14 15-34-12.webm](https://github.com/Alystrasz/NorthstarBlog/assets/40122905/f747fc4e-87a8-4c10-9bdd-c1b8a09995d0)

It's fine on mobile although still a bit too big:
![2023-11-14 15-37-27-0](https://github.com/Alystrasz/NorthstarBlog/assets/40122905/b243bb04-927f-4ed7-b103-32cd4944ed5b)

**Comment by Alystrasz** [comment]
I limited banner image height in 3e99fcadc41b11ac6d7b6279c7a11ee7409a0a00:

![image](https://github.com/Alystrasz/NorthstarBlog/assets/11993538/8e0e69e2-2a44-4e10-9792-2eeee97e7473)

LMK if it looks ok to you :)

**Comment by GeckoEidechse** [comment]
Looks fine from the screenshot. However it seems the changes are not reflected the same on the actual webpage when I pulled them?

![image](https://github.com/Alystrasz/NorthstarBlog/assets/40122905/c07b0bf8-a6d4-4b01-a762-426e914e3db0)

`git log` says it's on newes `gh-pages`, i.e. a6d3d0794ab493565fbf9115d150bea18adcb0be

**Comment by Alystrasz** [comment]
Newest style is applied to `.page__hero` container, not the image child.
Otherwise, I believe it's a caching issue, since I do see the newest style on the actual webpage:

![image](https://github.com/Alystrasz/NorthstarBlog/assets/11993538/1d1c7280-a2b4-4f57-bbc0-76d8919a1906)

Try to reload the webpage without caching (Ctrl+Shit+R I think)

**Comment by GeckoEidechse** [comment]
Yup was probably a caching issue cause checking the webpage now (regardless of force reload) shows the banner image properly scaled :D
